version: '3'
services:
  twingate-connector:
    image: twingate/connector:1
    container_name: twingate-unique-degu
    environment:
      - TWINGATE_NETWORK=mansurmusa
      - TWINGATE_ACCESS_TOKEN=eyJhbGciOiJFUzI1NiIsImtpZCI6Il9vcEVRMWQ4dFJpV0RBeEFYUEwxTWpObkhYLXlzUW9MYlotSllTRTFPSE0iLCJ0eXAiOiJEQVQifQ.eyJudCI6IkFOIiwiYWlkIjoiNDc0NTc4IiwiZGlkIjoiMjA3MTY2NyIsImp0aSI6ImVhYzdjNzQ5LTQ5Y2YtNGFlYy1hYjJlLTQ4NDlkZGI3MjhjOCIsImlzcyI6InR3aW5nYXRlIiwiYXVkIjoibWFuc3VybXVzYSIsImV4cCI6MTc0MjE4Mjg2MCwiaWF0IjoxNzQyMTc5MjYwLCJ2ZXIiOiI0IiwidGlkIjoiMTQwODYzIiwicm53IjoxNzQyMTc5NTMxLCJybmV0aWQiOiIxODQ0MDQifQ.B7OD764_vh8qbScaQ-Oter_wOhAbL-joA58KKSuodGtBqUvEdip6O5HFV8FCj0VqT-ozpbieAKZTOCu6HVZGyg
      - TWINGATE_REFRESH_TOKEN=kdKtLwoAoGK15I8m8lH4gebKlz6_0_D-HluGDpdwv36L1z8kpYpRsj2YXU31WbF3Vgf_JqBAoYKCFXn9RAm4MTeFqtlqJhMPY05EvX2e1RGg2oScvVPlk1HxNcBov7iwfmVbGA
      - TWINGATE_LABEL_HOSTNAME=twingate-connector
      - TWINGATE_LABEL_DEPLOYED_BY=docker-compose
      - TWINGATE_LOG_LEVEL=DEBUG
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "443:443/tcp"
      - "30000-31000:30000-31000/tcp"
      - "51820:51820/udp" 